# Generated by Django 2.0.7 on 2018-07-22 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('level', models.IntegerField()),
                ('vocacao', models.IntegerField(choices=[('D', 'Druid'), ('K', 'Knight'), ('S', 'Sorcerer'), ('P', 'Paladin'), ('ED', 'Elder Druid'), ('EK', 'Elite Knight'), ('MS', 'Master Sorcerer'), ('RP', 'Royal Paladin')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
