# Generated by Django 2.0.7 on 2018-07-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180722_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='vocacao',
            new_name='vocation',
        ),
    ]
