# Generated by Django 2.0.7 on 2018-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180723_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.TextField(choices=[('BL', 'Belobra'), ('GN', 'Gentebra')], default=1),
            preserve_default=False,
        ),
    ]
