# Generated by Django 2.0.7 on 2018-07-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180724_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='vocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Vocation'),
        ),
    ]
