# Generated by Django 2.0.7 on 2018-07-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_event_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='user',
            new_name='character',
        ),
    ]
