# Generated by Django 2.0.7 on 2018-08-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20180724_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('is_owner', models.NullBooleanField()),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.World')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Guild'),
        ),
    ]
